export const sampleCashflowCategories = [
  createCategorySeed('cash-cat-hoc-phi', 'Học phí', 'income'),
  createCategorySeed('cash-cat-sach-tai-lieu', 'Sách/tài liệu', 'both'),
  createCategorySeed('cash-cat-luong-giao-vien', 'Lương giáo viên', 'expense'),
  createCategorySeed('cash-cat-van-phong-pham', 'Văn phòng phẩm', 'expense'),
  createCategorySeed('cash-cat-mua-vat-tu-kho-hang', 'Mua vật tư / Kho hàng', 'expense'),
  createCategorySeed('cash-cat-thue-phong', 'Thuê phòng', 'expense'),
  createCategorySeed('cash-cat-marketing', 'Marketing', 'expense'),
  createCategorySeed('cash-cat-mua-dung-cu', 'Mua dụng cụ', 'expense'),
  createCategorySeed('cash-cat-le-phi-giai-dau', 'Lệ phí giải đấu', 'income'),
  createCategorySeed('cash-cat-khac', 'Khác', 'both'),
]

export const cashflowCategories = sampleCashflowCategories.map((category) => category.name)

export const cashflowMethods = ['Tiền mặt', 'Chuyển khoản', 'Khác']

function createCategorySeed(id, name, type) {
  return {
    id,
    name,
    type,
    isArchived: false,
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  }
}

export const sampleCashflowTransactions = [
  {
    id: 'cashflow-001',
    type: 'income',
    category: 'Học phí',
    amount: 1200000,
    transactionDate: '2026-06-01',
    method: 'Chuyển khoản',
    personName: 'PH Minh An',
    recordedBy: 'Admin DreamHome',
    note: 'Thu học phí tháng 6',
    sourceModule: 'manual',
    createdAt: '2026-06-01T08:30:00.000Z',
  },
  {
    id: 'cashflow-002',
    type: 'income',
    category: 'Học phí',
    amount: 600000,
    transactionDate: '2026-06-01',
    method: 'Tiền mặt',
    personName: 'PH Gia Bảo',
    recordedBy: 'Admin DreamHome',
    note: 'Đóng bổ sung nửa gói học',
    sourceModule: 'manual',
    createdAt: '2026-06-01T10:15:00.000Z',
  },
  {
    id: 'cashflow-003',
    type: 'expense',
    category: 'Lương giáo viên',
    amount: 2000000,
    transactionDate: '2026-06-01',
    method: 'Chuyển khoản',
    personName: 'Giáo viên phụ trách lớp cuối tuần',
    recordedBy: 'Admin DreamHome',
    note: 'Tạm chi lương buổi dạy',
    sourceModule: 'manual',
    createdAt: '2026-06-01T17:30:00.000Z',
  },
  {
    id: 'cashflow-004',
    type: 'income',
    category: 'Sách/tài liệu',
    amount: 150000,
    transactionDate: '2026-06-02',
    method: 'Tiền mặt',
    personName: 'PH Phương Nhi',
    recordedBy: 'Admin DreamHome',
    note: 'Thu tiền bộ tài liệu nhập môn',
    sourceModule: 'manual',
    createdAt: '2026-06-02T09:20:00.000Z',
  },
  {
    id: 'cashflow-005',
    type: 'expense',
    category: 'Văn phòng phẩm',
    amount: 180000,
    transactionDate: '2026-06-02',
    method: 'Tiền mặt',
    personName: 'Nhà in tài liệu',
    recordedBy: 'Admin DreamHome',
    note: 'In phiếu bài tập và bảng điểm danh',
    sourceModule: 'manual',
    createdAt: '2026-06-02T11:45:00.000Z',
  },
  {
    id: 'cashflow-006',
    type: 'expense',
    category: 'Thuê phòng',
    amount: 1500000,
    transactionDate: '2026-06-03',
    method: 'Chuyển khoản',
    personName: 'DreamHome Building',
    recordedBy: 'Admin DreamHome',
    note: 'Chi thuê phòng học tuần đầu tháng',
    sourceModule: 'manual',
    createdAt: '2026-06-03T08:00:00.000Z',
  },
  {
    id: 'cashflow-007',
    type: 'income',
    category: 'Khác',
    amount: 300000,
    transactionDate: '2026-06-03',
    method: 'Tiền mặt',
    personName: 'Nhóm học viên giải nội bộ',
    recordedBy: 'Admin DreamHome',
    note: 'Thu lệ phí giải đấu nhỏ',
    sourceModule: 'manual',
    createdAt: '2026-06-03T14:00:00.000Z',
  },
  {
    id: 'cashflow-008',
    type: 'expense',
    category: 'Marketing',
    amount: 350000,
    transactionDate: '2026-06-04',
    method: 'Chuyển khoản',
    personName: 'Dịch vụ thiết kế bài đăng',
    recordedBy: 'Admin DreamHome',
    note: 'Thiết kế poster tuyển sinh',
    sourceModule: 'manual',
    createdAt: '2026-06-04T09:10:00.000Z',
  },
  {
    id: 'cashflow-009',
    type: 'expense',
    category: 'Khác',
    amount: 500000,
    transactionDate: '2026-06-04',
    method: 'Tiền mặt',
    personName: 'Nhà cung cấp đồng hồ cờ',
    recordedBy: 'Admin DreamHome',
    note: 'Mua thêm đồng hồ cờ cho lớp nâng cao',
    sourceModule: 'manual',
    createdAt: '2026-06-04T15:25:00.000Z',
  },
  {
    id: 'cashflow-010',
    type: 'income',
    category: 'Học phí',
    amount: 900000,
    transactionDate: '2026-06-05',
    method: 'Chuyển khoản',
    personName: 'PH Khánh Linh',
    recordedBy: 'Admin DreamHome',
    note: 'Thu học phí còn lại',
    sourceModule: 'manual',
    createdAt: '2026-06-05T08:50:00.000Z',
  },
  {
    id: 'cashflow-011',
    type: 'expense',
    category: 'Văn phòng phẩm',
    amount: 120000,
    transactionDate: '2026-06-05',
    method: 'Tiền mặt',
    personName: 'Cửa hàng văn phòng phẩm',
    recordedBy: 'Admin DreamHome',
    note: 'Bút, giấy ghi chú, bìa hồ sơ',
    sourceModule: 'manual',
    createdAt: '2026-06-05T13:40:00.000Z',
  },
  {
    id: 'cashflow-012',
    type: 'income',
    category: 'Sách/tài liệu',
    amount: 220000,
    transactionDate: '2026-06-06',
    method: 'Khác',
    personName: 'PH Hải Đăng',
    recordedBy: 'Admin DreamHome',
    note: 'Thu tài liệu chiến thuật trung cấp',
    sourceModule: 'manual',
    createdAt: '2026-06-06T10:05:00.000Z',
  },
]
