export const inventoryCategories = [
  'Sách / tài liệu',
  'Bàn cờ / quân cờ',
  'Đồng hồ cờ',
  'Văn phòng phẩm',
  'Thiết bị lớp học',
  'Khác',
]

export const inventoryConditions = [
  'Đang dùng',
  'Cần bổ sung',
  'Hết hàng',
  'Hỏng / cần kiểm tra',
]

export const sampleInventoryItems = [
  {
    id: 'inv-book-tactics-intermediate',
    name: 'Sách chiến thuật trung cấp',
    category: 'Sách / tài liệu',
    unit: 'quyển',
    quantity: 12,
    lowStockThreshold: 3,
    condition: 'Đang dùng',
    location: 'Tủ tài liệu lớp 1',
    note: 'Dùng cho lớp nâng cao',
    updatedAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'inv-book-ichess-intro',
    name: 'Giáo trình nhập môn iChess',
    category: 'Sách / tài liệu',
    unit: 'quyển',
    quantity: 8,
    lowStockThreshold: 5,
    condition: 'Đang dùng',
    location: 'Kệ giáo trình DreamHome',
    note: 'Phát cho học viên mới khi cần',
    updatedAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'inv-board-standard-set',
    name: 'Bộ bàn cờ tiêu chuẩn',
    category: 'Bàn cờ / quân cờ',
    unit: 'bộ',
    quantity: 10,
    lowStockThreshold: 3,
    condition: 'Đang dùng',
    location: 'Kệ dụng cụ lớp lớn',
    note: 'Dùng hằng ngày cho lớp cơ bản',
    updatedAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'inv-piece-backup',
    name: 'Quân cờ dự phòng',
    category: 'Bàn cờ / quân cờ',
    unit: 'bộ',
    quantity: 4,
    lowStockThreshold: 2,
    condition: 'Đang dùng',
    location: 'Hộp dự phòng dưới bàn giáo viên',
    note: 'Bù quân thất lạc sau giờ học',
    updatedAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'inv-clock-basic',
    name: 'Đồng hồ cờ cơ bản',
    category: 'Đồng hồ cờ',
    unit: 'cái',
    quantity: 3,
    lowStockThreshold: 2,
    condition: 'Cần bổ sung',
    location: 'Tủ thiết bị lớp 2',
    note: 'Ưu tiên cho buổi luyện thi đấu',
    updatedAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'inv-clock-check',
    name: 'Đồng hồ cờ cần kiểm tra pin',
    category: 'Đồng hồ cờ',
    unit: 'cái',
    quantity: 1,
    lowStockThreshold: 2,
    condition: 'Hỏng / cần kiểm tra',
    location: 'Khay kỹ thuật',
    note: 'Một máy chập chờn nút bấm',
    updatedAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'inv-tactic-worksheet',
    name: 'Phiếu bài tập chiến thuật',
    category: 'Văn phòng phẩm',
    unit: 'tờ',
    quantity: 120,
    lowStockThreshold: 30,
    condition: 'Đang dùng',
    location: 'Ngăn photocopy',
    note: 'Dùng cho bài tập cuối buổi',
    updatedAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'inv-whiteboard-marker',
    name: 'Bút lông bảng',
    category: 'Văn phòng phẩm',
    unit: 'cây',
    quantity: 6,
    lowStockThreshold: 4,
    condition: 'Đang dùng',
    location: 'Ống bút bàn giáo viên',
    note: 'Gồm đen, xanh, đỏ',
    updatedAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'inv-demo-board',
    name: 'Bảng demo chiến thuật',
    category: 'Thiết bị lớp học',
    unit: 'cái',
    quantity: 1,
    lowStockThreshold: 1,
    condition: 'Đang dùng',
    location: 'Tường lớp lớn',
    note: 'Bảng nam châm cho giáo viên minh họa',
    updatedAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'inv-projector-cable',
    name: 'Dây HDMI máy chiếu',
    category: 'Thiết bị lớp học',
    unit: 'cái',
    quantity: 2,
    lowStockThreshold: 1,
    condition: 'Đang dùng',
    location: 'Hộp phụ kiện máy chiếu',
    note: 'Dùng khi chiếu ván mẫu',
    updatedAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'inv-internal-medal',
    name: 'Huy chương giải nội bộ',
    category: 'Khác',
    unit: 'cái',
    quantity: 0,
    lowStockThreshold: 5,
    condition: 'Hết hàng',
    location: 'Khay sự kiện',
    note: 'Cần đặt thêm trước giải tháng sau',
    updatedAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: 'inv-reward-sticker',
    name: 'Sticker thưởng học viên',
    category: 'Khác',
    unit: 'tờ',
    quantity: 20,
    lowStockThreshold: 10,
    condition: 'Đang dùng',
    location: 'Ngăn quà thưởng',
    note: 'Dùng thưởng hoàn thành thử thách',
    updatedAt: '2026-06-01T08:00:00.000Z',
  },
]
