export const modules = [
  {
    id: 'hoc-vien',
    name: 'Học viên',
    shortDescription: 'Quản lý hồ sơ học viên và theo dõi trạng thái học tập tại cơ sở.',
    status: 'in-progress',
    plannedFeatures: [
      'Xem danh sách học viên',
      'Tìm kiếm học viên',
      'Lọc theo trạng thái học',
      'Xem chi tiết học viên',
      'Ghi chú chăm sóc',
    ],
    plannedData: [
      'Thông tin học viên',
      'Thông tin phụ huynh',
      'Trạng thái học',
      'Lịch sử ghi chú chăm sóc',
    ],
  },
  {
    id: 'khach-hang-tu-van',
    name: 'Phụ huynh / Tư vấn',
    shortDescription: 'Theo dõi danh sách phụ huynh, khách tư vấn và trạng thái chăm sóc ban đầu.',
    status: 'in-progress',
    plannedFeatures: [
      'Xem danh sách phụ huynh và khách tư vấn',
      'Tìm kiếm theo tên, SĐT, học viên hoặc nhu cầu',
      'Lọc theo loại liên hệ, trạng thái chăm sóc và nguồn',
      'Chuẩn bị nền cho CRUD ở phase sau',
    ],
    plannedData: [
      'Tên phụ huynh / khách tư vấn',
      'Số điện thoại',
      'Học viên liên quan hoặc nhu cầu tư vấn',
      'Trạng thái chăm sóc',
      'Nguồn biết đến',
      'Ghi chú gần nhất',
    ],
  },
  {
    id: 'giao-vien',
    name: 'Giáo viên',
    shortDescription: 'Theo dõi danh sách giáo viên, liên hệ, trạng thái và hình thức hợp tác.',
    status: 'in-progress',
    plannedFeatures: [
      'Xem danh sách giáo viên',
      'Tìm kiếm giáo viên',
      'Lọc theo trạng thái',
      'Lọc theo loại giáo viên',
    ],
    plannedData: [
      'Thông tin giáo viên',
      'Thông tin liên hệ',
      'Trạng thái hoạt động',
      'Loại giáo viên',
      'Chuyên môn và cấp độ dạy',
    ],
  },
  {
    id: 'nhan-vien',
    name: 'Nhân viên',
    shortDescription: 'Theo dõi chấm công, địa điểm dạy và tổng buổi hoạt động của nhân sự/giáo viên.',
    status: 'in-progress',
    plannedFeatures: [
      'Bảng chấm công',
      'Tổng buổi theo ca dạy',
      'Lọc theo tuần, địa điểm dạy và nhân sự',
      'Tổng hợp từ giáo viên và thời khóa biểu hiện có',
    ],
    plannedData: [
      'Giáo viên / nhân sự',
      'Địa điểm dạy',
      'Ca/lớp',
      'Trạng thái chấm công',
    ],
  },
  {
    id: 'thoi-khoa-bieu',
    name: 'Thời khóa biểu',
    shortDescription: 'Chuẩn bị màn hình xem lịch dạy, lịch làm và lịch trực tại cơ sở.',
    status: 'planned',
    plannedFeatures: [
      'Xem lịch dạy',
      'Xem lịch làm/lịch trực',
      'Lọc theo ngày/tuần',
      'Lọc theo giáo viên/nhân viên',
    ],
    plannedData: [
      'Lịch theo ngày',
      'Lịch theo tuần',
      'Giáo viên phụ trách',
      'Nhân viên trực',
    ],
  },
  {
    id: 'hoc-phi',
    name: 'Học phí',
    shortDescription: 'Theo dõi học phí, gói học, số buổi và tình trạng thanh toán.',
    status: 'in-progress',
    plannedFeatures: [
      'Theo dõi gói học/khóa học',
      'Theo dõi số buổi',
      'Theo dõi đã đóng/còn nợ',
      'Cảnh báo sắp đến hạn/quá hạn',
    ],
    plannedData: [
      'Gói học',
      'Số buổi',
      'Khoản đã đóng',
      'Khoản còn nợ',
      'Mốc đến hạn',
    ],
  },
  {
    id: 'thu-chi',
    name: 'Thu chi',
    shortDescription: 'Ghi nhận khoản thu, khoản chi và tổng hợp giao dịch theo ngày.',
    status: 'in-progress',
    plannedFeatures: [
      'Ghi nhận khoản thu',
      'Ghi nhận khoản chi',
      'Tổng hợp thu chi theo ngày',
    ],
    plannedData: [
      'Khoản thu',
      'Khoản chi',
      'Ngày giao dịch',
      'Người ghi nhận',
    ],
  },
  {
    id: 'so-quy',
    name: 'Sổ quỹ',
    shortDescription: 'Theo dõi số dư quỹ, lịch sử đối soát và trạng thái chốt sổ nhẹ theo ngày.',
    status: 'in-progress',
    plannedFeatures: [
      'Xem tổng thu theo ngày',
      'Xem tổng chi theo ngày',
      'Thiết lập số dư đầu kỳ',
      'Xem chênh lệch trong ngày',
      'Đối soát quỹ cuối ngày',
      'Xem lịch sử đối soát',
      'Chốt sổ nhẹ theo ngày',
      'Theo dõi giao dịch trong ngày',
    ],
    plannedData: [
      'Giao dịch Thu chi',
      'Số dư đầu kỳ',
      'Ngày giao dịch',
      'Tổng thu',
      'Tổng chi',
      'Bản ghi đối soát',
      'Trạng thái chốt sổ',
    ],
  },
  {
    id: 'kho-hang',
    name: 'Kho hàng',
    shortDescription: 'Theo dõi vật tư, tài sản và tồn kho của cơ sở.',
    status: 'in-progress',
    plannedFeatures: [
      'Xem danh sách vật tư / tài sản',
      'Nhập kho',
      'Xuất kho',
      'Theo dõi tồn kho',
    ],
    plannedData: [
      'Thông tin vật tư / tài sản',
      'Phiếu nhập kho',
      'Phiếu xuất kho',
      'Số lượng tồn kho',
    ],
  },
  {
    id: 'bao-cao',
    name: 'Báo cáo',
    shortDescription: 'Tổng hợp báo cáo ngày, báo cáo tuần, thu chi và học/vắng/nghỉ từ dữ liệu hiện có.',
    status: 'in-progress',
    plannedFeatures: [
      'Báo cáo ngày',
      'Báo cáo tuần',
      'Biểu đồ thu/chi theo tuần',
      'Biểu đồ học/vắng/nghỉ tổng thể cơ sở',
      'In và tải báo cáo',
    ],
    plannedData: [
      'Công việc ngày',
      'Tình huống/vấn đề',
      'Doanh thu trong ngày',
      'Dữ liệu thu chi và điểm danh hiện có',
    ],
  },
  {
    id: 'cai-dat-co-so',
    name: 'Cài đặt cơ sở',
    shortDescription: 'Chuẩn bị cấu hình thông tin cơ sở và các dữ liệu nền cho vận hành.',
    status: 'in-progress',
    plannedFeatures: [
      'Thông tin cơ sở',
      'Quản lý ca học / lớp',
      'Cấu hình gói học',
      'Cấu hình trạng thái học viên',
      'Cấu hình dữ liệu mẫu',
    ],
    plannedData: [
      'Thông tin cơ sở',
      'Danh mục ca học / lớp',
      'Danh mục gói học',
      'Danh mục trạng thái học viên',
      'Dữ liệu mẫu',
    ],
  },
  {
    id: 'bang-diem-danh',
    name: 'Bảng điểm danh',
    shortDescription: 'Tự động tổng hợp bảng điểm danh theo tháng từ học viên, ca học/lớp và báo cáo buổi học.',
    status: 'in-progress',
    plannedFeatures: [
      'Xem bảng điểm danh theo tháng',
      'Lọc theo ca học / lớp',
      'Tìm kiếm học viên theo tên hoặc mã học viên',
      'Tổng hợp số buổi đã học từ báo cáo buổi học',
    ],
    plannedData: [
      'Mã học viên',
      'Ca học / lớp',
      'Ngày học trong tháng',
      'Số buổi đã học và số buổi còn lại',
    ],
  },
  {
    id: 'dang-cap-nhat',
    name: 'Đang cập nhật',
    shortDescription: 'Nơi giữ các module sẽ bổ sung sau khi phạm vi sản phẩm rõ hơn.',
    status: 'placeholder',
    plannedFeatures: ['Nơi giữ các module sẽ bổ sung sau'],
    plannedData: ['Danh sách ý tưởng module', 'Ghi chú phạm vi tương lai'],
  },
]
