export const scheduleDays = [
  { id: 'monday', label: 'Thứ 2' },
  { id: 'tuesday', label: 'Thứ 3' },
  { id: 'wednesday', label: 'Thứ 4' },
  { id: 'thursday', label: 'Thứ 5' },
  { id: 'friday', label: 'Thứ 6' },
  { id: 'saturday', label: 'Thứ 7' },
  { id: 'sunday', label: 'Chủ nhật' },
]

export const scheduleLevels = ['beginner', 'intermediate', 'advanced', 'mixed']
export const scheduleStatuses = ['scheduled', 'done', 'cancelled']
export const scheduleTypes = ['recurring', 'oneOff']
export const scheduleOccurrenceReasons = [
  { id: 'makeup', label: 'Học bù', shortLabel: 'Học bù' },
  { id: 'trial', label: 'Học thử', shortLabel: 'Học thử' },
  { id: 'extra', label: 'Học thêm', shortLabel: 'Học thêm' },
  { id: 'event', label: 'Sự kiện', shortLabel: 'Sự kiện' },
  { id: 'other', label: 'Khác', shortLabel: 'Đột xuất' },
]

export const sampleScheduleSessions = [
  {
    id: 'schedule-001',
    scheduleType: 'recurring',
    title: 'Lớp Cờ vua căn bản A',
    dayOfWeek: 'monday',
    startDate: '2026-06-01',
    endDate: '2026-09-01',
    date: null,
    occurrenceReason: '',
    startTime: '18:00',
    endTime: '19:30',
    room: 'Phòng 1',
    teacherName: 'Thầy Khôi',
    groupName: 'Nhóm căn bản',
    level: 'beginner',
    status: 'scheduled',
    note: 'Lớp nhập môn cho học viên mới.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'schedule-002',
    scheduleType: 'recurring',
    title: 'Lớp Chiến thuật trung cấp',
    dayOfWeek: 'tuesday',
    startDate: '2026-06-01',
    endDate: '2026-09-01',
    date: null,
    occurrenceReason: '',
    startTime: '19:30',
    endTime: '21:00',
    room: 'Phòng 2',
    teacherName: 'Cô Anh',
    groupName: 'Nhóm trung cấp',
    level: 'intermediate',
    status: 'scheduled',
    note: 'Tập trung bài chiến thuật và trung cuộc.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'schedule-003',
    scheduleType: 'oneOff',
    title: 'Kèm 1-1 khai cuộc',
    dayOfWeek: 'wednesday',
    startDate: null,
    endDate: null,
    date: '2026-06-03',
    occurrenceReason: 'trial',
    startTime: '17:30',
    endTime: '18:30',
    room: 'Phòng 1',
    teacherName: 'Thầy Bảo',
    groupName: 'Kèm cá nhân',
    level: 'intermediate',
    status: 'scheduled',
    note: 'Buổi mẫu 1-1.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'schedule-004',
    scheduleType: 'recurring',
    title: 'Lớp thiếu nhi nhập môn',
    dayOfWeek: 'monday',
    startDate: '2026-06-01',
    endDate: '2026-08-31',
    date: null,
    occurrenceReason: '',
    startTime: '18:00',
    endTime: '19:00',
    room: 'Phòng 3',
    teacherName: 'Cô Linh',
    groupName: 'Nhóm thiếu nhi',
    level: 'beginner',
    status: 'scheduled',
    note: 'Lớp nhỏ tuổi.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'schedule-005',
    scheduleType: 'recurring',
    title: 'Luyện giải cuối tuần',
    dayOfWeek: 'saturday',
    startDate: '2026-06-01',
    endDate: '2026-09-01',
    date: null,
    occurrenceReason: '',
    startTime: '08:30',
    endTime: '10:00',
    room: 'Phòng 2',
    teacherName: 'Cô Anh',
    groupName: 'Nhóm luyện giải',
    level: 'advanced',
    status: 'scheduled',
    note: 'Giải bài và phân tích ván.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'schedule-006',
    scheduleType: 'recurring',
    title: 'Endgame cơ bản',
    dayOfWeek: 'saturday',
    startDate: '2026-06-01',
    endDate: '2026-09-01',
    date: null,
    occurrenceReason: '',
    startTime: '15:00',
    endTime: '16:30',
    room: 'Phòng 1',
    teacherName: 'Thầy Huy',
    groupName: 'Nhóm tàn cuộc',
    level: 'intermediate',
    status: 'scheduled',
    note: 'Tốt, vua, xe cơ bản.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'schedule-007',
    scheduleType: 'recurring',
    title: 'Lớp nhóm căn bản B',
    dayOfWeek: 'sunday',
    startDate: '2026-06-01',
    endDate: '2026-09-01',
    date: null,
    occurrenceReason: '',
    startTime: '09:00',
    endTime: '10:30',
    room: 'Phòng 3',
    teacherName: 'Thầy Tùng',
    groupName: 'Nhóm căn bản',
    level: 'beginner',
    status: 'scheduled',
    note: 'Lớp cuối tuần.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'schedule-008',
    scheduleType: 'oneOff',
    title: 'Tư duy cờ vua nâng cao',
    dayOfWeek: 'friday',
    startDate: null,
    endDate: null,
    date: '2026-06-05',
    occurrenceReason: 'extra',
    startTime: '19:00',
    endTime: '20:30',
    room: 'Phòng 2',
    teacherName: 'Thầy Khôi',
    groupName: 'Nhóm nâng cao',
    level: 'advanced',
    status: 'scheduled',
    note: 'Phân tích thế cờ và kế hoạch.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
]
