export const studentStatuses = ['Đang theo học', 'Bảo lưu', 'Ngưng học']

export const studentLevels = ['Nhập môn', 'Cơ bản', 'Trung cấp', 'Nâng cao']

export const botMilestones = [
  'Chưa có',
  'Người Mới',
  'Turtle 1',
  'Turtle 2',
  'Turtle 3',
  'Bee 1',
  'Bee 2',
  'Bee 3',
]

export const sampleStudents = [
  {
    id: 'stu-001',
    fullName: 'Nguyễn Minh An',
    birthDate: '2016-03-12',
    avatarUrl: '',
    schoolName: 'Tiểu học Sao Mai',
    hometown: 'Hà Nội',
    hobbies: 'Cờ vua, đọc truyện, vẽ',
    nationality: 'Việt Nam',
    parentName: 'Nguyễn Thu Hà',
    parentBirthYear: 1987,
    parentPhone: '0901001001',
    parentJob: 'Kế toán',
    parentArea: 'Quận 7',
    level: 'Cơ bản',
    elo: 650,
    mainTeacherName: 'Chưa phân công',
    classSessionIds: ['class-session-t7-1500', 'class-session-t4t6-1900'],
    testScore: 7,
    highestBotMilestone: 'Turtle 3',
    personality: 'Tập trung, hơi rụt rè khi vào lớp mới',
    currentStatus: 'Đang theo học',
    achievements: 'Hoàn thành giải nội bộ tháng 4',
    parentNotes: 'Phụ huynh muốn con luyện thêm khai cuộc đơn giản.',
    latestCareNote: 'Cần nhắc lịch học bù vào cuối tuần.',
    careNotes: [
      {
        id: 'note_legacy_2026_05_25',
        createdAt: '2026-05-25T09:00:00.000Z',
        author: 'Admin DreamHome',
        content: 'Cần nhắc lịch học bù vào cuối tuần.',
        tags: [],
      },
    ],
    createdAt: '2026-05-01',
    updatedAt: '2026-05-25',
  },
  {
    id: 'stu-002',
    fullName: 'Trần Gia Bảo',
    birthDate: '2015-09-21',
    avatarUrl: '',
    schoolName: 'Tiểu học DreamHome',
    hometown: 'Đà Nẵng',
    hobbies: 'Bóng đá, cờ vua',
    nationality: 'Việt Nam',
    parentName: 'Trần Minh Quân',
    parentBirthYear: 1984,
    parentPhone: '0902002002',
    parentJob: 'Kỹ sư xây dựng',
    parentArea: 'Nhà Bè',
    level: 'Trung cấp',
    elo: 900,
    mainTeacherName: 'Chưa phân công',
    classSessionIds: ['class-session-t7cn-1030'],
    testScore: 8.5,
    highestBotMilestone: 'Bee 1',
    personality: 'Năng động, thích thi đấu',
    currentStatus: 'Đang theo học',
    achievements: 'Top 3 mini tournament lớp thứ Bảy',
    parentNotes: 'Gia đình ưu tiên lịch học tối thứ Ba.',
    latestCareNote: 'Đã trao đổi phụ huynh về tăng bài tập chiến thuật.',
    careNotes: [
      {
        id: 'note_legacy_2026_05_28',
        createdAt: '2026-05-28T09:00:00.000Z',
        author: 'Admin DreamHome',
        content: 'Đã trao đổi phụ huynh về tăng bài tập chiến thuật.',
        tags: [],
      },
    ],
    createdAt: '2026-05-02',
    updatedAt: '2026-05-28',
  },
  {
    id: 'stu-003',
    fullName: 'Lê Phương Nhi',
    birthDate: '2017-01-08',
    avatarUrl: '',
    schoolName: 'Tiểu học Nguyễn Văn Trỗi',
    hometown: 'Bình Định',
    hobbies: 'Piano, tô màu',
    nationality: 'Việt Nam',
    parentName: 'Lê Hoàng Yến',
    parentBirthYear: 1990,
    parentPhone: '0903003003',
    parentJob: 'Giáo viên',
    parentArea: 'Quận 4',
    level: 'Nhập môn',
    elo: 400,
    mainTeacherName: 'Chưa phân công',
    classSessionIds: ['class-session-t7cn-1730'],
    testScore: 6,
    highestBotMilestone: 'Turtle 1',
    personality: 'Cẩn thận, cần thêm tự tin khi phát biểu',
    currentStatus: 'Đang theo học',
    achievements: 'Nhớ tốt luật nhập thành và phong cấp',
    parentNotes: 'Phụ huynh cần báo tiến độ mỗi 2 tuần.',
    latestCareNote: 'Gửi bài luyện quân mã cho phụ huynh.',
    careNotes: [
      {
        id: 'note_legacy_2026_05_20',
        createdAt: '2026-05-20T09:00:00.000Z',
        author: 'Admin DreamHome',
        content: 'Gửi bài luyện quân mã cho phụ huynh.',
        tags: [],
      },
    ],
    createdAt: '2026-05-04',
    updatedAt: '2026-05-20',
  },
  {
    id: 'stu-004',
    fullName: 'Phạm Đức Huy',
    birthDate: '2014-11-17',
    avatarUrl: '',
    schoolName: 'THCS Lê Quý Đôn',
    hometown: 'TP. Hồ Chí Minh',
    hobbies: 'Lập trình, cờ vua',
    nationality: 'Việt Nam',
    parentName: 'Phạm Quốc Dũng',
    parentBirthYear: 1982,
    parentPhone: '0904004004',
    parentJob: 'Quản lý dự án',
    parentArea: 'Thủ Đức',
    level: 'Nâng cao',
    elo: 1200,
    mainTeacherName: 'Chưa phân công',
    testScore: 9,
    highestBotMilestone: 'Bee 3',
    personality: 'Tư duy nhanh, đôi khi vội vàng',
    currentStatus: 'Bảo lưu',
    achievements: 'Đạt huy chương bạc giải phong trào quận',
    parentNotes: 'Tạm nghỉ do lịch thi học kỳ.',
    latestCareNote: 'Hẹn liên hệ lại đầu tháng sau.',
    careNotes: [
      {
        id: 'note_legacy_2026_05_24',
        createdAt: '2026-05-24T09:00:00.000Z',
        author: 'Admin DreamHome',
        content: 'Hẹn liên hệ lại đầu tháng sau.',
        tags: [],
      },
    ],
    createdAt: '2026-05-05',
    updatedAt: '2026-05-24',
  },
  {
    id: 'stu-005',
    fullName: 'Võ Khánh Linh',
    birthDate: '2016-07-30',
    avatarUrl: '',
    schoolName: 'Tiểu học Hoa Sen',
    hometown: 'Cần Thơ',
    hobbies: 'Cờ vua, bơi lội',
    nationality: 'Việt Nam',
    parentName: 'Võ Thị Mai',
    parentBirthYear: 1988,
    parentPhone: '0905005005',
    parentJob: 'Chủ cửa hàng',
    parentArea: 'Bình Thạnh',
    level: 'Cơ bản',
    elo: 680,
    mainTeacherName: 'Chưa phân công',
    testScore: 7.5,
    highestBotMilestone: 'Turtle 2',
    personality: 'Chăm chỉ, hay hỏi lại để chắc bài',
    currentStatus: 'Đang theo học',
    achievements: 'Hoàn thành chuỗi bài chiếu hết 1 nước',
    parentNotes: 'Phụ huynh muốn nhận bài tập qua tin nhắn.',
    latestCareNote: 'Đã ghi chú cần luyện tàn cuộc vua tốt.',
    careNotes: [
      {
        id: 'note_legacy_2026_05_26',
        createdAt: '2026-05-26T09:00:00.000Z',
        author: 'Admin DreamHome',
        content: 'Đã ghi chú cần luyện tàn cuộc vua tốt.',
        tags: [],
      },
    ],
    createdAt: '2026-05-07',
    updatedAt: '2026-05-26',
  },
  {
    id: 'stu-006',
    fullName: 'Đặng Nhật Nam',
    birthDate: '2015-05-19',
    avatarUrl: '',
    schoolName: 'Tiểu học Trần Quốc Toản',
    hometown: 'Huế',
    hobbies: 'Robot, truyện tranh',
    nationality: 'Việt Nam',
    parentName: 'Đặng Anh Khoa',
    parentBirthYear: 1985,
    parentPhone: '0906006006',
    parentJob: 'Bác sĩ',
    parentArea: 'Quận 1',
    level: 'Trung cấp',
    elo: 860,
    mainTeacherName: 'Chưa phân công',
    testScore: 8,
    highestBotMilestone: 'Bee 2',
    personality: 'Điềm tĩnh, thích phân tích lâu',
    currentStatus: 'Đang theo học',
    achievements: 'Tăng 12 điểm bài test chiến thuật',
    parentNotes: 'Cần tránh xếp lịch trùng lớp tiếng Anh.',
    latestCareNote: 'Đã báo phụ huynh về tiến bộ trong trung cuộc.',
    careNotes: [
      {
        id: 'note_legacy_2026_05_27',
        createdAt: '2026-05-27T09:00:00.000Z',
        author: 'Admin DreamHome',
        content: 'Đã báo phụ huynh về tiến bộ trong trung cuộc.',
        tags: [],
      },
    ],
    createdAt: '2026-05-09',
    updatedAt: '2026-05-27',
  },
  {
    id: 'stu-007',
    fullName: 'Bùi Hải Đăng',
    birthDate: '2013-12-03',
    avatarUrl: '',
    schoolName: 'THCS Nam Sài Gòn',
    hometown: 'Nghệ An',
    hobbies: 'Cầu lông, cờ vua',
    nationality: 'Việt Nam',
    parentName: 'Bùi Thanh Tâm',
    parentBirthYear: 1981,
    parentPhone: '0907007007',
    parentJob: 'Kinh doanh',
    parentArea: 'Quận 8',
    level: 'Nâng cao',
    elo: 1180,
    mainTeacherName: 'Chưa phân công',
    testScore: 9,
    highestBotMilestone: 'Bee 3',
    personality: 'Cạnh tranh cao, cần giữ bình tĩnh khi thua',
    currentStatus: 'Ngưng học',
    achievements: 'Từng tham gia đội tuyển trường',
    parentNotes: 'Gia đình chuyển lịch sinh hoạt, chưa hẹn ngày quay lại.',
    latestCareNote: 'Đã xác nhận ngưng học, giữ lịch sử học tập.',
    careNotes: [
      {
        id: 'note_legacy_2026_05_22',
        createdAt: '2026-05-22T09:00:00.000Z',
        author: 'Admin DreamHome',
        content: 'Đã xác nhận ngưng học, giữ lịch sử học tập.',
        tags: [],
      },
    ],
    createdAt: '2026-05-11',
    updatedAt: '2026-05-22',
  },
  {
    id: 'stu-008',
    fullName: 'Hoàng Mai Chi',
    birthDate: '2017-10-14',
    avatarUrl: '',
    schoolName: 'Tiểu học Ánh Dương',
    hometown: 'Đồng Nai',
    hobbies: 'Nhảy, xếp hình',
    nationality: 'Việt Nam',
    parentName: 'Hoàng Lan Anh',
    parentBirthYear: 1991,
    parentPhone: '0908008008',
    parentJob: 'Nhân viên văn phòng',
    parentArea: 'Quận 2',
    level: 'Nhập môn',
    elo: 420,
    mainTeacherName: 'Chưa phân công',
    testScore: 6.5,
    highestBotMilestone: 'Chưa có',
    personality: 'Vui vẻ, cần luyện thói quen ghi nhớ lượt đi',
    currentStatus: 'Bảo lưu',
    achievements: 'Nắm chắc cách đi của các quân cơ bản',
    parentNotes: 'Bảo lưu 2 tuần vì lịch gia đình.',
    latestCareNote: 'Nhắc phụ huynh xác nhận lịch học lại.',
    careNotes: [
      {
        id: 'note_legacy_2026_05_29',
        createdAt: '2026-05-29T09:00:00.000Z',
        author: 'Admin DreamHome',
        content: 'Nhắc phụ huynh xác nhận lịch học lại.',
        tags: [],
      },
    ],
    createdAt: '2026-05-12',
    updatedAt: '2026-05-29',
  },
]
