export const teacherStatuses = ['active', 'paused', 'inactive']

export const teacherTypes = ['fulltime', 'parttime', 'collaborator']

export const sampleTeachers = [
  {
    id: 'teacher-001',
    fullName: 'Nguyễn Minh Khôi',
    displayName: 'Thầy Khôi',
    phone: '0901234567',
    email: 'minhkhoi.ichess@gmail.com',
    loginEmail: 'minhkhoi.ichess@gmail.com',
    birthYear: '1995',
    hometown: 'Hà Nội',
    currentArea: 'Quận 7, TP.HCM',
    accountStatus: 'not_invited',
    status: 'active',
    teacherType: 'fulltime',
    specialties: ['Cờ vua căn bản', 'Lớp thiếu nhi'],
    levels: ['beginner', 'intermediate'],
    mainRole: 'Giáo viên cờ vua',
    assignedClassNames: ['Lớp nhập môn T2-T4', 'Lớp thiếu nhi cơ bản'],
    assignedStudentIds: ['student-001', 'student-002', 'student-003'],
    currentStudentCount: 12,
    note: 'Ưu tiên lớp thiếu nhi mới bắt đầu.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'teacher-002',
    fullName: 'Trần Hoàng Anh',
    displayName: 'Cô Anh',
    phone: '0912345678',
    email: 'hoanganh.ichess@gmail.com',
    loginEmail: 'hoanganh.ichess@gmail.com',
    birthYear: '1996',
    hometown: 'Đà Nẵng',
    currentArea: 'Bình Thạnh, TP.HCM',
    accountStatus: 'not_invited',
    status: 'active',
    teacherType: 'parttime',
    specialties: ['Chiến thuật trung cuộc', 'Luyện giải'],
    levels: ['intermediate', 'advanced'],
    mainRole: 'Giáo viên luyện giải',
    assignedClassNames: ['Lớp luyện giải cuối tuần', 'Lớp nâng cao T3-T5'],
    assignedStudentIds: ['student-004', 'student-005'],
    currentStudentCount: 10,
    note: 'Có thể phụ trách nhóm nâng cao.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'teacher-003',
    fullName: 'Lê Quốc Bảo',
    displayName: 'Thầy Bảo',
    phone: '0923456789',
    email: 'quocbao.ichess@gmail.com',
    loginEmail: 'quocbao.ichess@gmail.com',
    birthYear: '1994',
    hometown: 'Huế',
    currentArea: 'Thủ Đức, TP.HCM',
    accountStatus: 'not_invited',
    status: 'paused',
    teacherType: 'collaborator',
    specialties: ['Khai cuộc', 'Kèm 1-1'],
    levels: ['intermediate'],
    mainRole: 'Giáo viên cộng tác',
    assignedClassNames: ['Kèm 1-1 khai cuộc'],
    assignedStudentIds: ['student-006'],
    currentStudentCount: 4,
    note: 'Tạm nghỉ trong tháng này.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'teacher-004',
    fullName: 'Phạm Ngọc Linh',
    displayName: 'Cô Linh',
    phone: '0934567890',
    email: 'ngoclinh.ichess@gmail.com',
    loginEmail: 'ngoclinh.ichess@gmail.com',
    birthYear: '1998',
    hometown: 'Đồng Nai',
    currentArea: 'Quận 2, TP.HCM',
    accountStatus: 'not_invited',
    status: 'active',
    teacherType: 'collaborator',
    specialties: ['Lớp nhập môn', 'Tư duy cờ vua'],
    levels: ['beginner'],
    mainRole: 'Giáo viên cộng tác',
    assignedClassNames: ['Lớp nhập môn cuối tuần'],
    assignedStudentIds: ['student-007', 'student-008'],
    currentStudentCount: 8,
    note: 'Phù hợp lớp nhỏ tuổi.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'teacher-005',
    fullName: 'Đỗ Gia Huy',
    displayName: 'Thầy Huy',
    phone: '0945678901',
    email: 'giahuy.ichess@gmail.com',
    loginEmail: 'giahuy.ichess@gmail.com',
    birthYear: '1993',
    hometown: 'Cần Thơ',
    currentArea: 'Quận 10, TP.HCM',
    accountStatus: 'not_invited',
    status: 'inactive',
    teacherType: 'parttime',
    specialties: ['Cờ nhanh', 'Endgame'],
    levels: ['advanced'],
    mainRole: 'Giáo viên bán thời gian',
    assignedClassNames: ['Lớp cờ nhanh nâng cao'],
    assignedStudentIds: [],
    currentStudentCount: 0,
    note: 'Đã ngừng dạy, giữ lại dữ liệu để tra cứu.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'teacher-006',
    fullName: 'Võ Thanh Tùng',
    displayName: 'Thầy Tùng',
    phone: '0956789012',
    email: 'thanhtung.ichess@gmail.com',
    loginEmail: 'thanhtung.ichess@gmail.com',
    birthYear: '1997',
    hometown: 'Bình Dương',
    currentArea: 'Phú Nhuận, TP.HCM',
    accountStatus: 'not_invited',
    status: 'active',
    teacherType: 'fulltime',
    specialties: ['Nền tảng chiến thuật', 'Lớp nhóm'],
    levels: ['beginner', 'intermediate'],
    mainRole: 'Giáo viên cờ vua',
    assignedClassNames: ['Lớp nhóm nền tảng', 'Lớp chiến thuật cơ bản'],
    assignedStudentIds: ['student-009', 'student-010'],
    currentStudentCount: 14,
    note: 'Có thể đứng lớp nhóm đông học viên.',
    createdAt: '2026-06-04T00:00:00.000Z',
    updatedAt: '2026-06-04T00:00:00.000Z',
  },
]
