-- R2.1: extend the existing Ca soft-delete guard; no business backfill/cascade.
begin;

create or replace function public.class_session_safe_delete_guard()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.entity_type <> 'class_session'
     or old.deleted_at is not null
     or new.deleted_at is null then
    return new;
  end if;

  -- A3 assignments/events remain history even after their effective range ends.
  -- C5.1 and A3 serialize on the same Ca row. No new advisory lock/order.
  if exists (
    select 1 from public.center_class_teacher_assignments assignment
    where assignment.center_id = old.center_id
      and assignment.class_session_local_id = old.local_id
  ) or exists (
    select 1 from public.a3_teacher_events event
    where event.center_id = old.center_id
      and event.class_session_local_id = old.local_id
  ) then
    raise exception 'class_session_delete_referenced';
  end if;

  -- Every persisted A2 occurrence is a materialized, durable context fact,
  -- including PLANNED/CANCELLED. Virtual future slots generated by a fresh Ca
  -- have no row here and do not make that genuinely unused Ca undeletable.
  if exists (
    select 1 from public.center_schedule_occurrences occurrence
    where occurrence.center_id = old.center_id
      and occurrence.class_session_local_id = old.local_id
  ) then
    raise exception 'class_session_delete_referenced';
  end if;

  -- Preserve existing current/ended Student enrollment and legacy references.
  if exists (
    select 1 from public.center_student_recurring_enrollments enrollment
    where enrollment.center_id = old.center_id
      and enrollment.class_session_local_id = old.local_id
  ) then
    raise exception 'class_session_delete_referenced';
  end if;

  if exists (
    select 1 from public.center_cloud_entities student
    where student.center_id = old.center_id
      and student.entity_type = 'student'
      and (
        (
          pg_catalog.jsonb_typeof(student.payload->'classSessionIds') = 'array'
          and (student.payload->'classSessionIds') @> pg_catalog.jsonb_build_array(old.local_id)
        )
        or exists (
          select 1 from pg_catalog.jsonb_array_elements(
            case when pg_catalog.jsonb_typeof(student.payload->'recurringEnrollments') = 'array'
              then student.payload->'recurringEnrollments' else '[]'::jsonb end
          ) enrollment_item
          where pg_catalog.btrim(coalesce(enrollment_item->>'classSessionId',
            enrollment_item->>'class_session_id', '')) = old.local_id
        )
      )
  ) then
    raise exception 'class_session_delete_referenced';
  end if;

  if exists (
    select 1 from public.center_cloud_entities schedule
    where schedule.center_id = old.center_id
      and schedule.entity_type = 'schedule_session'
      and pg_catalog.btrim(coalesce(schedule.payload->>'classSessionId', '')) = old.local_id
  ) then
    raise exception 'class_session_delete_referenced';
  end if;

  if exists (
    select 1 from public.center_cloud_entities history
    where history.center_id = old.center_id
      and history.entity_type in ('attendance_record', 'session_report')
      and (
        pg_catalog.btrim(coalesce(history.payload->>'classSessionId', '')) = old.local_id
        or exists (
          select 1 from public.center_cloud_entities schedule
          where schedule.center_id = old.center_id
            and schedule.entity_type = 'schedule_session'
            and pg_catalog.btrim(coalesce(schedule.payload->>'classSessionId', '')) = old.local_id
            and schedule.local_id in (
              pg_catalog.btrim(coalesce(history.payload->>'scheduleSessionId', '')),
              pg_catalog.btrim(coalesce(history.payload->>'sessionId', ''))
            )
        )
      )
  ) then
    raise exception 'class_session_delete_referenced';
  end if;
  return new;
end
$$;

commit;
